services:
  backend:
    container_name: blitzrechnung-api
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared

  frontend:
    container_name: blitzrechnung-web
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/app/shared
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  shared-data:
